version: '3.8'

services:
  postgres-sales:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_sales_data:/var/lib/postgresql/data

  postgres-delivery:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delivery_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_delivery_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data

  delivery:
    build:
      context: .
      dockerfile: apps/delivery/Dockerfile
    depends_on:
      postgres-delivery:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      POSTGRES_HOST: postgres-delivery
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delivery_db
      KAFKA_BROKERS: kafka:9093
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always

  sales:
    build:
      context: .
      dockerfile: apps/sales/Dockerfile
    depends_on:
      postgres-sales:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      POSTGRES_HOST: postgres-sales
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_db
      KAFKA_BROKERS: kafka:9093
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always

volumes:
  postgres_sales_data:
  postgres_delivery_data:
  kafka_data:
